MiscSection:NewButton("Summon Car", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/faded-yarls/car-spawn/main/car.lua"))()
end)
MiscSection:NewToggle("Auto TP Kill", function() -- rage tp aura end)
MiscSection:NewToggle("Explode Landmines", function() -- kaboom all landmines end)
MiscSection:NewButton("Change Player ID (UserID Swap)", function() -- spoof userid + name end)